<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMLfj84y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMLfj84y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMLfj84y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMLfj84y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMLfj84y\App_KernelDevDebugContainer([
    'container.build_hash' => 'MLfj84y',
    'container.build_id' => 'cbb33dd4',
    'container.build_time' => 1656950162,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMLfj84y');
